name: Hello World Workflow

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Echo "Hello World" and "Welcome"
      - name: Print Greetings
        run: |
          echo "Hello World"
          echo "Welcome"
